version: '3'
services:

  database:
    image: postgres:alpine
    container_name: rentalx-database
    build: .docker/postgres
    restart: always
    env_file: ./.env
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sa1234
      - POSTGRES_DB=rentalx
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    restart: always
    container_name: rentalx-app
    env_file: ./.env
    ports:
      - 3333:3333
      - 9230:9229
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local