version: '3.9'
services:

  database:
    image: postgres
    container_name: database
    build: .docker/postgres
    restart: always
    tty: true
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sa1234
      - POSTGRES_DB=rentalx
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
      
  app:
    build: .
    restart: always
    container_name: rentalx
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app

volumes:
  pgdata:
    driver: local