version: '3.9'
services:

  database:
    image: postgres
    container_name: rentalx-database
    build: .docker/postgres
    restart: always
    tty: true
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_HOST=rentalx-database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sa1234
      - POSTGRES_DB=rentalx
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    restart: always
    container_name: rentalx-app
    ports:
      - 3333:3333
      - 9230:9229
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local